name: SwiftLint

on:  
  workflow_call:

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-swift@v2
      - name: GitHub Actions for SwiftLint
        uses: sinoru/actions-swiftlint@v6