name: run-tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  install_dependencies:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Tuist cache
        uses: actions/cache@v3
        with:
          key: '"tuist cache" | Project.swift | .package.resolved'
          path: Tuist/Cache
      - name: Generate project
        run: |
          curl -Ls https://install.tuist.io | bash
          tuist fetch
          tuist cache warm --profile Release --dependencies-only
          tuist generate --profile Release --no-open
  test:
    runs-on: macos-latest
    needs: [install_dependencies, generate]
    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: bundle install
      - name: Run tests
        run: bundle exec fastlane test