name: run-tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  install_dependencies:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2'
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Tuist cache
        uses: actions/cache@v3
        with:
          key: '"tuist cache" | Project.swift | .package.resolved'
          path: Tuist/Cache
      - name: Generate project
        run: |
          curl -Ls https://install.tuist.io | bash
          tuist fetch
          tuist cache warm --profile Release --dependencies-only
          tuist generate --profile Release --no-open
      - name: Archive generated files
        uses: actions/upload-artifact@v2
        with:
          name: generated-artifact
          path: "."
  test:
    runs-on: macos-latest
    needs: [install_dependencies, generate]
    steps:
      - name: Download generated files
        uses: actions/download-artifact@v2
        with:
          name: generated-artifact
          path: "."
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2'
      - name: Run tests
        run: bundle exec fastlane test